repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.1.5
    hooks:
      # Run the linter.
      - id: ruff
        args:
         [
          "--fix",
          #"--quiet",  # Uncomment this to ignore any errors
         ]
      # Run the formatter.
      - id: ruff-format